"""
Content of the synthetic NexaCore Technologies document corpus.

Every fact written here is also listed in data/fact_sheet.yaml so that
parser fidelity and RAG answers can be checked against a known ground truth.
Amounts use "INR" instead of the rupee symbol so every PDF font renders them.

Block types:
  ("h1", text) ("h2", text) ("p", text) ("bullets", [items]) ("table", [header, *rows])
XLSX documents use "sheets": {sheet_name: [header, *rows]}.
"""

ORG = "NexaCore Technologies Pvt. Ltd."

DOCUMENTS = [
    # ------------------------------------------------------------------ HR
    {
        "file": "HR/HR_Leave_Policy_2025.pdf",
        "department": "HR", "doc_type": "Policy", "title": "Leave Policy",
        "version": "2025.1", "effective_date": "2025-04-01", "status": "superseded",
        "access_level": "internal", "owner": "Head of HR",
        "blocks": [
            ("h1", "Leave Policy (Version 2025.1)"),
            ("p", "Effective date: 01 April 2025. Policy owner: Head of HR. This version is superseded by Leave Policy 2026.1."),
            ("h2", "1. Purpose"),
            ("p", "This policy sets out the leave entitlements available to all permanent employees of NexaCore Technologies."),
            ("h2", "2. Leave Entitlements"),
            ("table", [["Leave type", "Entitlement", "Notes"],
                       ["Annual leave", "18 days per year", "Accrues monthly"],
                       ["Sick leave", "10 days per year", "Medical certificate needed beyond 2 consecutive days"],
                       ["Maternity leave", "26 weeks", "As per Maternity Benefit Act"],
                       ["Paternity leave", "5 days", "To be availed within 3 months of birth"]]),
            ("h2", "3. Carry Forward"),
            ("p", "Employees may carry forward a maximum of 5 days of unused annual leave to the next calendar year. Any balance above 5 days lapses on 31 December."),
            ("h2", "4. Work From Home"),
            ("p", "Employees may work from home for up to 2 days per week with prior approval from their reporting manager."),
            ("h2", "5. Applying for Leave"),
            ("bullets", ["Apply on the HRMS portal at least 7 days in advance for planned leave.",
                         "Unplanned leave must be informed to the manager before 10:00 AM on the same day.",
                         "Leave without approval is treated as unauthorised absence."]),
        ],
    },
    {
        "file": "HR/HR_Leave_Policy_2026.pdf",
        "department": "HR", "doc_type": "Policy", "title": "Leave Policy",
        "version": "2026.1", "effective_date": "2026-04-01", "status": "current",
        "access_level": "internal", "owner": "Head of HR",
        "blocks": [
            ("h1", "Leave Policy (Version 2026.1)"),
            ("p", "Effective date: 01 April 2026. Policy owner: Head of HR. This version replaces Leave Policy 2025.1."),
            ("h2", "1. Purpose"),
            ("p", "This policy sets out the leave entitlements available to all permanent employees of NexaCore Technologies."),
            ("h2", "2. Leave Entitlements"),
            ("table", [["Leave type", "Entitlement", "Notes"],
                       ["Annual leave", "20 days per year", "Accrues monthly"],
                       ["Sick leave", "12 days per year", "Medical certificate needed beyond 2 consecutive days"],
                       ["Maternity leave", "26 weeks", "As per Maternity Benefit Act"],
                       ["Paternity leave", "10 days", "To be availed within 6 months of birth"]]),
            ("h2", "3. Carry Forward"),
            ("p", "Employees may carry forward a maximum of 10 days of unused annual leave to the next calendar year. Any balance above 10 days lapses on 31 December."),
            ("h2", "4. Work From Home"),
            ("p", "Employees may work from home for up to 3 days per week with prior approval from their reporting manager."),
            ("h2", "5. Applying for Leave"),
            ("bullets", ["Apply on the HRMS portal at least 7 days in advance for planned leave.",
                         "Unplanned leave must be informed to the manager before 10:00 AM on the same day.",
                         "Leave without approval is treated as unauthorised absence."]),
            ("h2", "6. Summary of Changes from 2025.1"),
            ("bullets", ["Annual leave increased from 18 to 20 days.",
                         "Sick leave increased from 10 to 12 days.",
                         "Carry forward limit increased from 5 to 10 days.",
                         "Work from home increased from 2 to 3 days per week.",
                         "Paternity leave increased from 5 to 10 days."]),
        ],
    },
    {
        "file": "HR/HR_Employee_Handbook.docx",
        "department": "HR", "doc_type": "Handbook", "title": "Employee Handbook",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Head of HR",
        "blocks": [
            ("h1", "Employee Handbook"),
            ("p", "Version 2026.1, effective 01 January 2026. Applies to all employees of NexaCore Technologies."),
            ("h2", "1. Working Hours"),
            ("p", "Standard working hours are 9:30 AM to 6:30 PM, Monday to Friday. Core collaboration hours are 11:00 AM to 4:00 PM."),
            ("h2", "2. Probation and Confirmation"),
            ("p", "New employees serve a probation period of 6 months. Confirmation is based on a performance review by the reporting manager."),
            ("h2", "3. Notice Period"),
            ("table", [["Employee category", "Notice period"],
                       ["During probation", "15 days"],
                       ["Confirmed employees", "60 days"],
                       ["Managers and above", "90 days"]]),
            ("h2", "4. Expense Claims"),
            ("p", "Employees should submit business expense claims within 45 days of incurring the expense. Please refer to the Finance Expense Reimbursement Policy for limits."),
            ("h2", "5. Grievance Redressal"),
            ("p", "An employee may raise a grievance with the HR Business Partner within 30 days of the incident. HR will acknowledge the grievance within 3 working days."),
            ("h2", "6. Code of Conduct"),
            ("bullets", ["Treat colleagues, customers and vendors with respect.",
                         "Declare any conflict of interest to HR in writing.",
                         "Gifts from vendors above INR 2,000 in value must be declined."]),
        ],
    },
    {
        "file": "HR/HR_Benefits_by_Grade.xlsx",
        "department": "HR", "doc_type": "Benefits Schedule", "title": "Benefits by Grade",
        "version": "2026.1", "effective_date": "2026-04-01", "status": "current",
        "access_level": "restricted", "owner": "Head of HR",
        "sheets": {
            "Benefits": [["Grade", "Designation band", "Health insurance cover (INR)", "Monthly meal allowance (INR)", "Annual learning budget (INR)"],
                         ["G1", "Associate", "3,00,000", "2,200", "15,000"],
                         ["G2", "Senior Associate", "5,00,000", "2,200", "25,000"],
                         ["G3", "Manager", "7,50,000", "3,000", "40,000"],
                         ["G4", "Senior Manager", "10,00,000", "3,000", "60,000"],
                         ["G5", "Director", "15,00,000", "4,000", "1,00,000"]],
            "Notes": [["Item", "Detail"],
                      ["Insurance family cover", "Employee, spouse and two children"],
                      ["Parental cover", "Optional top-up paid by employee"],
                      ["Learning budget", "Unused budget does not carry forward"]],
        },
    },
    # ------------------------------------------------------------- Finance
    {
        "file": "Finance/FIN_Expense_Reimbursement_Policy.pdf",
        "department": "Finance", "doc_type": "Policy", "title": "Expense Reimbursement Policy",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Chief Financial Officer",
        "blocks": [
            ("h1", "Expense Reimbursement Policy"),
            ("p", "Version 2026.1, effective 01 January 2026. Policy owner: Chief Financial Officer."),
            ("h2", "1. Submission Timeline"),
            ("p", "All expense claims must be submitted on the Finance portal within 30 days of the date of expense. Claims submitted after 30 days will be rejected unless approved by the Finance Controller."),
            ("h2", "2. Receipts"),
            ("p", "Original receipts are mandatory for any single expense above INR 500."),
            ("h2", "3. Travel Limits"),
            ("table", [["Expense head", "Metro cities", "Non-metro cities"],
                       ["Daily allowance (per diem)", "INR 3,000", "INR 2,000"],
                       ["Hotel (per night, G1 to G3)", "INR 7,000", "INR 4,500"],
                       ["Hotel (per night, G4 and G5)", "INR 12,000", "INR 8,000"]]),
            ("p", "Air travel is permitted in economy class only for flights under 4 hours."),
            ("h2", "4. Reimbursement"),
            ("p", "Approved claims are reimbursed to the salary account within 10 working days of approval."),
            ("h2", "5. Non-reimbursable Items"),
            ("bullets", ["Alcohol and tobacco.", "Traffic fines and penalties.", "Personal entertainment and minibar charges."]),
        ],
    },
    {
        "file": "Finance/FIN_Approval_Matrix.xlsx",
        "department": "Finance", "doc_type": "Approval Matrix", "title": "Purchase Approval Matrix",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Finance Controller",
        "sheets": {
            "Purchase Approvals": [["Purchase value range (INR)", "Approver", "Additional requirement"],
                                   ["Up to 50,000", "Department Manager", "None"],
                                   ["50,001 to 2,00,000", "Department Head", "Budget code required"],
                                   ["2,00,001 to 10,00,000", "Finance Controller", "Three quotations required"],
                                   ["Above 10,00,000", "CFO and CEO jointly", "Board note for capital items"]],
            "Refund Approvals": [["Refund value (INR)", "Approver"],
                                 ["Up to 50,000", "Customer Service Manager"],
                                 ["Above 50,000", "Finance Controller"]],
        },
    },
    {
        "file": "Finance/FIN_Vendor_Payment_Terms.docx",
        "department": "Finance", "doc_type": "Procedure", "title": "Vendor Payment Terms",
        "version": "2026.1", "effective_date": "2026-02-01", "status": "current",
        "access_level": "restricted", "owner": "Finance Controller",
        "blocks": [
            ("h1", "Vendor Payment Terms"),
            ("p", "Version 2026.1, effective 01 February 2026. Owner: Finance Controller."),
            ("h2", "1. Standard Payment Terms"),
            ("p", "Vendor invoices are paid within 45 days of receipt of a valid invoice (Net 45)."),
            ("h2", "2. Invoice Requirements"),
            ("bullets", ["Invoice must quote a valid Purchase Order (PO) number.",
                         "Vendor GSTIN must match the vendor master record.",
                         "Invoices without a PO number are returned to the vendor."]),
            ("h2", "3. Bank Detail Verification"),
            ("p", "Before the first payment, Finance verifies vendor bank details using a cancelled cheque and a penny-drop test."),
            ("h2", "4. Advance Payments"),
            ("p", "Advance payments are capped at 20% of the PO value and require Finance Controller approval."),
        ],
    },
    # ------------------------------------------------------------------ IT
    {
        "file": "IT/IT_Information_Security_Policy.pdf",
        "department": "IT", "doc_type": "Policy", "title": "Information Security Policy",
        "version": "2026.1", "effective_date": "2026-01-15", "status": "current",
        "access_level": "internal", "owner": "Chief Information Security Officer",
        "blocks": [
            ("h1", "Information Security Policy"),
            ("p", "Version 2026.1, effective 15 January 2026. Owner: Chief Information Security Officer (CISO)."),
            ("h2", "1. Passwords and Authentication"),
            ("bullets", ["Passwords must be at least 12 characters long.",
                         "Passwords must be changed every 90 days.",
                         "Multi-factor authentication (MFA) is mandatory for email, VPN and all cloud applications."]),
            ("h2", "2. Device Security"),
            ("p", "All company laptops must have full-disk encryption enabled. Screens must lock automatically after 5 minutes of inactivity."),
            ("h2", "3. Incident Reporting"),
            ("p", "Any suspected security incident, including phishing emails, must be reported to security@nexacore.example within 2 hours of detection."),
            ("h2", "4. Data Classification"),
            ("table", [["Class", "Examples", "Handling"],
                       ["Public", "Marketing brochures", "No restriction"],
                       ["Internal", "Policies, org charts", "Share inside NexaCore only"],
                       ["Confidential", "Contracts, salary data", "Need-to-know, encrypted in transit"],
                       ["Restricted", "Customer personal data", "Named access, encrypted at rest and in transit"]]),
            ("h2", "5. Acceptable Use"),
            ("p", "Personal USB storage devices are blocked on company laptops. Only software from the approved catalogue may be installed."),
        ],
    },
    {
        "file": "IT/IT_Asset_Management_Policy.docx",
        "department": "IT", "doc_type": "Policy", "title": "IT Asset Management Policy",
        "version": "2026.1", "effective_date": "2026-01-15", "status": "current",
        "access_level": "internal", "owner": "IT Manager",
        "blocks": [
            ("h1", "IT Asset Management Policy"),
            ("p", "Version 2026.1, effective 15 January 2026. Owner: IT Manager."),
            ("h2", "1. Laptop Allocation and Refresh"),
            ("p", "Every employee is issued one laptop. Laptops are refreshed every 4 years or earlier if declared beyond economical repair by IT."),
            ("h2", "2. Lost or Stolen Devices"),
            ("p", "A lost or stolen laptop must be reported to the IT Service Desk within 24 hours. IT will remotely wipe the device. An FIR copy is required for stolen devices."),
            ("h2", "3. Software Requests"),
            ("p", "Software requests are raised on the ServiceDesk portal and approved by the IT Manager. Approved requests are fulfilled within 3 business days."),
            ("h2", "4. Asset Return"),
            ("p", "Exiting employees must return all IT assets on or before their last working day. Unreturned assets are recovered from the full and final settlement."),
        ],
    },
    {
        "file": "IT/IT_Vendor_Security_Checklist.xlsx",
        "department": "IT", "doc_type": "Checklist", "title": "Vendor Security Assessment Checklist",
        "version": "2026.1", "effective_date": "2026-01-15", "status": "current",
        "access_level": "internal", "owner": "CISO",
        "sheets": {
            "Checklist": [["Control", "Requirement", "Mandatory for"],
                          ["ISO 27001 certificate", "Valid certificate or equivalent SOC 2 Type II report", "Tier 1 and Tier 2 vendors"],
                          ["Data Processing Agreement", "Signed DPA before any personal data is shared", "Vendors handling personal data"],
                          ["Penetration test report", "Report dated within the last 12 months", "Tier 1 vendors"],
                          ["MFA on vendor accounts", "MFA enabled on all accounts accessing NexaCore systems", "All vendors with system access"]],
            "Risk Tiers": [["Tier", "Definition", "Reassessment frequency"],
                           ["Tier 1", "Access to customer personal data or production systems", "Every 12 months"],
                           ["Tier 2", "Access to internal data only", "Every 24 months"],
                           ["Tier 3", "No data or system access", "At onboarding only"]],
        },
    },
    # --------------------------------------------------------- Procurement
    {
        "file": "Procurement/PROC_Procurement_Policy.pdf",
        "department": "Procurement", "doc_type": "Policy", "title": "Procurement Policy",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Head of Procurement",
        "blocks": [
            ("h1", "Procurement Policy"),
            ("p", "Version 2026.1, effective 01 January 2026. Owner: Head of Procurement."),
            ("h2", "1. Quotations"),
            ("p", "At least three written quotations are required for any purchase above INR 1,00,000. Single-source purchases require a written justification approved by the Head of Procurement."),
            ("h2", "2. Purchase Orders"),
            ("p", "A Purchase Order must be issued before any goods are delivered or work begins. Work started without a PO will not be paid."),
            ("h2", "3. Vendor Onboarding Process"),
            ("p", "New vendors are onboarded through the following steps, owned by different departments:"),
            ("table", [["Step", "Activity", "Owner department"],
                       ["1", "Business team raises a vendor request form on the procurement portal", "Procurement"],
                       ["2", "Vendor KYC: PAN, GSTIN and certificate of incorporation", "Procurement"],
                       ["3", "Security assessment for vendors that access data or systems", "IT"],
                       ["4", "NDA and Master Services Agreement signed", "Legal"],
                       ["5", "Bank detail verification", "Finance"],
                       ["6", "Vendor code created in ERP", "Procurement"]]),
            ("p", "The complete onboarding process should be finished within 7 working days of receiving all documents."),
            ("h2", "4. Vendor Performance Review"),
            ("p", "Active vendors are reviewed annually using the Vendor Evaluation Matrix. Vendors scoring below 70 are placed on a performance improvement plan."),
        ],
    },
    {
        "file": "Procurement/PROC_Vendor_Evaluation_Matrix.xlsx",
        "department": "Procurement", "doc_type": "Evaluation Matrix", "title": "Vendor Evaluation Matrix",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Head of Procurement",
        "sheets": {
            "Criteria": [["Criterion", "Weight (%)", "How it is measured"],
                         ["Price competitiveness", "35", "Comparison with other quotations"],
                         ["Quality", "25", "Defect rate and rework"],
                         ["Delivery timeliness", "20", "Percentage of on-time deliveries"],
                         ["Compliance", "10", "KYC, security and legal documents complete"],
                         ["Service and support", "10", "Response time to issues"]],
            "Score Bands": [["Total score", "Outcome"],
                            ["85 and above", "Preferred vendor"],
                            ["70 to 84", "Approved vendor"],
                            ["Below 70", "Performance improvement plan"]],
        },
    },
    # --------------------------------------------------------------- Legal
    {
        "file": "Legal/LEGAL_Contract_Management_Policy.pdf",
        "department": "Legal", "doc_type": "Policy", "title": "Contract Management Policy",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "General Counsel",
        "blocks": [
            ("h1", "Contract Management Policy"),
            ("p", "Version 2026.1, effective 01 January 2026. Owner: General Counsel."),
            ("h2", "1. Contract Review"),
            ("p", "All contracts must be reviewed by the Legal team before signature. The standard review turnaround time is 5 business days."),
            ("h2", "2. Signing Authority"),
            ("table", [["Contract value (INR)", "Legal reviewer", "Authorised signatory"],
                       ["Up to 25,00,000", "Legal Counsel", "Department Head"],
                       ["25,00,001 to 1,00,00,000", "General Counsel", "CFO"],
                       ["Above 1,00,00,000", "General Counsel", "CEO"]]),
            ("h2", "3. Contract Retention"),
            ("p", "Signed contracts are stored in the contract repository and retained for 8 years after expiry or termination."),
            ("h2", "4. Renewals"),
            ("p", "Contract owners must start renewal discussions at least 60 days before contract expiry."),
        ],
    },
    {
        "file": "Legal/LEGAL_NDA_Standard_Terms.docx",
        "department": "Legal", "doc_type": "Legal Template", "title": "NDA Standard Terms",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "restricted", "owner": "General Counsel",
        "blocks": [
            ("h1", "Non-Disclosure Agreement: Standard Terms"),
            ("p", "Version 2026.1. For use by Legal Counsel only. Deviations from these terms require General Counsel approval."),
            ("h2", "1. Type of NDA"),
            ("p", "NexaCore uses a mutual NDA template for vendors and partners. One-way NDAs are used only for candidate interviews involving confidential projects."),
            ("h2", "2. Confidentiality Period"),
            ("p", "Confidentiality obligations survive for 3 years after termination of the agreement. Trade secrets remain protected indefinitely."),
            ("h2", "3. Governing Law and Jurisdiction"),
            ("p", "The NDA is governed by the laws of India. Courts in New Delhi have exclusive jurisdiction."),
            ("h2", "4. Return of Information"),
            ("p", "On termination, the receiving party must return or destroy confidential information within 15 days and certify destruction in writing."),
        ],
    },
    {
        "file": "Legal/LEGAL_Data_Privacy_Policy.docx",
        "department": "Legal", "doc_type": "Policy", "title": "Data Privacy Policy",
        "version": "2026.1", "effective_date": "2026-03-01", "status": "current",
        "access_level": "internal", "owner": "Data Protection Officer",
        "blocks": [
            ("h1", "Data Privacy Policy"),
            ("p", "Version 2026.1, effective 01 March 2026. Owner: Data Protection Officer (DPO). Aligned with the Digital Personal Data Protection Act, 2023."),
            ("h2", "1. Personal Data Breach"),
            ("p", "Any personal data breach must be reported internally to the Data Protection Officer within 6 hours of discovery."),
            ("h2", "2. Data Principal Requests"),
            ("p", "Requests from customers to access, correct or erase their personal data must be completed within 30 days."),
            ("h2", "3. Retention"),
            ("p", "Customer personal data is retained for 3 years after account closure and then deleted or anonymised."),
            ("h2", "4. Consent"),
            ("p", "Marketing communication is sent only to customers who have given explicit opt-in consent."),
        ],
    },
    # ---------------------------------------------------- Customer Service
    {
        "file": "Customer_Service/CS_Service_Level_Agreement.pdf",
        "department": "Customer_Service", "doc_type": "Service Level Agreement", "title": "Customer Service Level Agreement",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Head of Customer Experience",
        "blocks": [
            ("h1", "Customer Service Level Agreement"),
            ("p", "Version 2026.1, effective 01 January 2026. Applies to all enterprise customers of the NexaCore Cloud platform."),
            ("h2", "1. Response and Resolution Targets"),
            ("table", [["Priority", "Definition", "First response", "Resolution target"],
                       ["P1", "Platform down for all users", "1 hour", "8 hours"],
                       ["P2", "Major feature unavailable", "4 hours", "24 hours"],
                       ["P3", "Minor issue or question", "1 business day", "5 business days"]]),
            ("h2", "2. Platform Availability"),
            ("p", "NexaCore commits to 99.5% monthly uptime, excluding scheduled maintenance announced 72 hours in advance."),
            ("h2", "3. Service Credits"),
            ("p", "If monthly uptime falls below 99.5%, the customer receives a service credit of 10% of the monthly fee. Below 98%, the credit is 25%."),
            ("h2", "4. Support Hours"),
            ("p", "P1 support is available 24x7. P2 and P3 support is available 9:00 AM to 9:00 PM IST on business days."),
        ],
    },
    {
        "file": "Customer_Service/CS_Complaint_and_Refund_Policy.docx",
        "department": "Customer_Service", "doc_type": "Policy", "title": "Complaint Handling and Refund Policy",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Head of Customer Experience",
        "blocks": [
            ("h1", "Complaint Handling and Refund Policy"),
            ("p", "Version 2026.1, effective 01 January 2026. Owner: Head of Customer Experience."),
            ("h2", "1. Acknowledgement"),
            ("p", "Every customer complaint must be acknowledged within 24 hours with a ticket number."),
            ("h2", "2. Escalation"),
            ("bullets", ["Level 1 support owns the complaint for the first 48 hours.",
                         "Unresolved complaints move to Level 2 support after 48 hours.",
                         "Complaints unresolved after 5 business days are escalated to the Head of Customer Experience."]),
            ("h2", "3. Refunds"),
            ("p", "Customers may request a refund within 30 days of the invoice date. Approved refunds are processed within 7 working days. Refunds above INR 50,000 require Finance Controller approval."),
            ("h2", "4. Complaint Closure"),
            ("p", "A complaint is closed only after the customer confirms resolution or does not respond for 7 days after the resolution is shared."),
        ],
    },
    {
        "file": "Customer_Service/CS_Escalation_Matrix.xlsx",
        "department": "Customer_Service", "doc_type": "Escalation Matrix", "title": "Customer Escalation Matrix",
        "version": "2026.1", "effective_date": "2026-01-01", "status": "current",
        "access_level": "internal", "owner": "Head of Customer Experience",
        "sheets": {
            "Escalation": [["Level", "Role", "Contact channel", "Escalate after"],
                           ["L1", "Support Executive", "support@nexacore.example", "48 hours"],
                           ["L2", "Senior Support Engineer", "l2-support@nexacore.example", "5 business days"],
                           ["L3", "Head of Customer Experience", "cx-head@nexacore.example", "Final level"]],
        },
    },
]
